type Objective = { text: string; completed: boolean };
type Resource = { title: string; type: string; url: string; source: string; readTime: number };

export interface ModuleSummaryInput {
  courseTitle: string;
  courseTopic: string;
  difficulty: string;
  weekNumber: number;
  moduleTitle: string;
  description: string;
  objectives: Objective[];
  resources: Resource[];
}

/** Build a structured study document from module data (offline fallback) */
export function buildFallbackModuleSummary(input: ModuleSummaryInput): string {
  const objectivesList = input.objectives
    .map((o, i) => `${i + 1}. ${o.text}`)
    .join('\n');

  const resourcesList = input.resources
    .map((r) => `- **${r.title}** (${r.type}, ~${r.readTime} min) — ${r.source}${r.url ? `\n  - Link: ${r.url}` : ''}`)
    .join('\n');

  return `# Week ${input.weekNumber} Study Guide

## Course: ${input.courseTitle}
**Topic:** ${input.courseTopic}  
**Level:** ${input.difficulty}  
**Module:** ${input.moduleTitle}

---

## Week ${input.weekNumber} Overview

${input.description}

This document covers all learning material for Week ${input.weekNumber}, including objectives, core concepts, and recommended resources.

---

## Learning Objectives

By the end of this week you should be able to:

${objectivesList || '- Review the module description and complete all activities.'}

---

## Week ${input.weekNumber} Content

### Core concepts

${input.description}

### Key topics to focus on

1. Understand the foundational ideas introduced in this module.
2. Work through each objective systematically.
3. Use the resources below to deepen your understanding.
4. Complete the quiz and assignment to reinforce learning.

---

## Recommended Resources

${resourcesList || '_No external resources listed. Use the AI Tutor for additional explanations._'}

---

## Study plan for this week

| Day | Activity |
|-----|----------|
| Day 1–2 | Read the overview and objectives |
| Day 3–4 | Complete resources and take notes |
| Day 5 | Take the knowledge quiz |
| Day 6–7 | Complete the coding assignment |

---

## Next steps

- Complete the **Knowledge Quiz** for this week.
- Submit the **Coding Assignment**.
- Mark the module complete when finished.

_Generated by NeuralLearn — Week ${input.weekNumber} summary document._
`;
}
